name: Raisintine

env:
  MIRROR_URL: 'git@github.com:EpitechPromo2026/B-DOP-200-RUN-2-1-chocolatine-raphael.turpin.git'
  EXECUTABLES: ''

on: push

jobs:
  check_repository_cleanliness:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Detect File
        run: |
          find -name "#*#" -printf "::error title=Unwanted file detected,file=%f::%f\n" >> tmp.txt
          find -name "*~" -printf "::error title=Unwanted file detected,file=%f::%f\n" >> tmp.txt
          # FILES=${FILES}\n${TMP}
          # FILES=$FILES$'\n'$(find -iname "*pain_au_chocolat*" -printf "::error title=Unwanted file detected,file=%f::%f\n")
          # FILES=$FILES$'\n'$(find -name "*.o" -printf "::error title=Unwanted file detected,file=%f::%f\n")
          # FILES=$FILES$'\n'$(find -name "*.a" -printf "::error title=Unwanted file detected,file=%f::%f\n")
          # FILES=$FILES$'\n'$(find -name "*.so" -printf "::error title=Unwanted file detected,file=%f::%f\n")
          # FILES=$FILES$'\n'$(find -name "*.gcno" -printf "::error title=Unwanted file detected,file=%f::%f\n")
          # FILES=$FILES$'\n'$(find -name "*.gcda" -printf "::error title=Unwanted file detected,file=%f::%f\n")
          # FILES=$FILES$'\n'$(find -name "*.gcov" -printf "::error title=Unwanted file detected,file=%f::%f\n")
          # echo -e $FILES
          cat tmp.txt