name: Raisintine

env:
  MIRROR_URL: 'git@github.com:EpitechPromo2026/B-DOP-200-RUN-2-1-chocolatine-raphael.turpin.git'
  EXECUTABLES: ''

on: push

jobs:
  check_repository_cleanliness:
    name: Repository is clean
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Detect File
        run: |
          touch.tmp.txt
          find -name "#*#" -printf "::error title=Unwanted file detected,file=%f::%p\n" >> tmp.txt
          find -name "*~" -printf "::error title=Unwanted file detected,file=%f::%p\n" >> tmp.txt
          find -iname "*pain_au_chocolat*" -printf "::error title=Unwanted file detected,file=%f::%p\n" >> tmp.txt
          find -name "*.o" -printf "::error title=Unwanted file detected,file=%f::%p\n" >> tmp.txt
          find -name "*.a" -printf "::error title=Unwanted file detected,file=%f::%p\n" >> tmp.txt
          find -name "*.so" -printf "::error title=Unwanted file detected,file=%f::%p\n" >> tmp.txt
          find -name "*.gcno" -printf "::error title=Unwanted file detected,file=%f::%p\n" >> tmp.txt
          find -name "*.gcda" -printf "::error title=Unwanted file detected,file=%f::%p\n" >> tmp.txt
          find -name "*.gcov" -printf "::error title=Unwanted file detected,file=%f::%p\n" >> tmp.txt
          find -path "./*tmp/*" -printf "::error title=Unwanted file detected,file=%f::%p\n" >> tmp.txt
          cat tmp.txt
          if [ ! -z tmp.txt ]; exit 1; fi

  check_program_compilation:
    needs: check_repository_cleanliness
    name: Program compiles
    runs-on: ubuntu-latest
    steps:
      - name: Compiles
        run: ls