name: Raisintine

env:
  MIRROR_URL: 'git@github.com:EpitechPromo2026/B-DOP-200-RUN-2-1-chocolatine-raphael.turpin.git'
  EXECUTABLES: ''

on: push

jobs:
  check_repository_cleanliness:
    steps:
      - run: find -name "*~"